workflows:
  ios-workflow:
    name: iOS Build

    max_build_duration: 60

    environment:
      xcode: 16.3
      cocoapods: default
      node: 20.11.1

      vars:
        RCT_NEW_ARCH_ENABLED: "0"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.towrides.app

    scripts:
      - name: Remove junk files
        script: |
          rm -rf __MACOSX

      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps

      - name: Clean Pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update

      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/TowRides.xcworkspace" \
            --scheme "TowRides"

    artifacts:
      - build/ios/ipa/*.ipa
