workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean & Install
        script: |
          rm -rf node_modules
          rm -rf package-lock.json
          npm install --legacy-peer-deps

      - name: Install Pods
        script: |
          cd ios
          pod install

      - name: Build iOS
        script: |
          xcodebuild -workspace ios/*.xcworkspace \
          -scheme TowRides \
          -configuration Release \
          -sdk iphoneos \
          -allowProvisioningUpdates \
          -archivePath build/TowRides.xcarchive archive

    artifacts:
      - build/**/*.ipa
